# Clippy configuration
avoid-breaking-exported-api = false
msrv = "1.70.0"
cognitive-complexity-threshold = 30
type-complexity-threshold = 250
single-char-binding-names-threshold = 4
trivial-copy-size-limit = 128
pass-by-value-size-limit = 256
too-many-arguments-threshold = 7
too-many-lines-threshold = 100
verbose-bit-mask-threshold = 1
literal-representation-threshold = 10
allow-expect-in-tests = true
allow-unwrap-in-tests = true
warn-on-all-wildcard-imports = false
disallowed-names = ["foo", "baz", "quux"]