#!/bin/sh
# comply:disable=COMPLY-002
# Generated by Rash v6.62.0
# POSIX-compliant shell script

set -euf
IFS=' 	
'
export LC_ALL=C

# Rash runtime functions
rash_println() {
    printf '%s\n' "$1"
}

# Main script begins
main() {
        key='name'
        val='test'
        rash_println "{"${key}": "${val}"}"
}

# Cleanup on exit
trap 'rm -rf "${TMPDIR:-/tmp}/rash.$$"' EXIT

# Execute main function
main "$@"
