#!/bin/sh
# Generated by Rash v6.60.0
# POSIX-compliant shell script

set -euf
IFS=' 	
'
export LC_ALL=C

# Rash runtime functions
rash_println() {
    printf '%s\n' "$1"
}

dispatch() {
    code="$1"

        case $((code % 6)) in
            0)
            base='10'
            ;;
            1)
            base='20'
            ;;
            2)
            base='30'
            ;;
            3)
            base='40'
            ;;
            4)
            base='50'
            ;;
            *)
            base='60'
            ;;
        esac
        adjusted=$((base + code))
        echo "$adjusted"
        return
}


# Main script begins
main() {
        a="$(dispatch 7)"
        b="$(dispatch 13)"
        c="$(dispatch 25)"
        rash_println $((a + b + c))
}

# Cleanup on exit
trap 'rm -rf "${TMPDIR:-/tmp}/rash.$$"' EXIT

# Execute main function
main "$@"
