#!/bin/sh
# Generated by Rash v6.60.0
# POSIX-compliant shell script

set -euf
IFS=' 	
'
export LC_ALL=C

# Rash runtime functions
rash_println() {
    printf '%s\n' "$1"
}

# Main script begins
main() {
        items_0='Alpha'
        items_1='Beta'
        values_0='10'
        values_1='20'
        for i in $(seq 0 1); do
            rash_println "${items_0} & ${values_0} \\"
        done
}

# Cleanup on exit
trap 'rm -rf "${TMPDIR:-/tmp}/rash.$$"' EXIT

# Execute main function
main "$@"
