#!/bin/sh
# Test Suite for Makefile.tested
# Generated by bashrs make purify --with-tests

set -e  # Exit on first failure

# Test: Determinism - same make invocation produces same output
test_determinism() {
    printf "Testing determinism for Makefile.tested...\n"

    # Run make twice and capture output
    make -f "Makefile.tested" > /tmp/output1.txt 2>&1 || true
    make -f "Makefile.tested" > /tmp/output2.txt 2>&1 || true

    # Sort outputs before comparing (handles make's parallel execution)
    sort /tmp/output1.txt > /tmp/output1_sorted.txt
    sort /tmp/output2.txt > /tmp/output2_sorted.txt

    # Compare sorted outputs
    if diff /tmp/output1_sorted.txt /tmp/output2_sorted.txt > /dev/null; then
        printf "✓ Determinism test passed\n"
        rm -f /tmp/output1.txt /tmp/output2.txt /tmp/output1_sorted.txt /tmp/output2_sorted.txt
        return 0
    else
        printf "✗ Determinism test failed - outputs differ\n"
        printf "First run (sorted):\n"
        cat /tmp/output1_sorted.txt
        printf "\nSecond run (sorted):\n"
        cat /tmp/output2_sorted.txt
        rm -f /tmp/output1.txt /tmp/output2.txt /tmp/output1_sorted.txt /tmp/output2_sorted.txt
        return 1
    fi
}

# Test: Idempotency - safe to re-run multiple times
test_idempotency() {
    printf "Testing idempotency for Makefile.tested...\n"

    # Run make three times
    make -f "Makefile.tested" > /dev/null 2>&1 || true
    make -f "Makefile.tested" > /dev/null 2>&1 || exit_code1=$?
    make -f "Makefile.tested" > /dev/null 2>&1 || exit_code2=$?

    # Second and third runs should succeed (exit code 0)
    if [ "${exit_code1:-0}" -eq 0 ] && [ "${exit_code2:-0}" -eq 0 ]; then
        printf "✓ Idempotency test passed\n"
        return 0
    else
        printf "✗ Idempotency test failed - not safe to re-run\n"
        return 1
    fi
}

# Test: POSIX Compliance - Makefile is POSIX-compatible
test_posix_compliance() {
    printf "Testing POSIX compliance for Makefile.tested...\n"

    # Check if Makefile can be parsed by POSIX make
    # (Most systems have GNU make, so we just verify it doesn't error)
    if make -f "Makefile.tested" --version > /dev/null 2>&1; then
        printf "✓ POSIX compliance test passed\n"
        return 0
    else
        printf "⚠ Could not verify POSIX compliance (make may not be available)\n"
        return 0  # Don't fail if make is not available
    fi
}

# Test Runner
run_all_tests() {
    printf "\n=== Running Test Suite ===\n\n"

    failed=0
    passed=0

    # Run determinism test
    if test_determinism; then
        passed=$((passed + 1))
    else
        failed=$((failed + 1))
    fi

    printf "\n"

    # Run idempotency test
    if test_idempotency; then
        passed=$((passed + 1))
    else
        failed=$((failed + 1))
    fi

    printf "\n"

    # Run posix_compliance test
    if test_posix_compliance; then
        passed=$((passed + 1))
    else
        failed=$((failed + 1))
    fi

    printf "\n"

    printf "\n=== Test Summary ===\n"
    printf "Passed: %d\n" "$passed"
    printf "Failed: %d\n" "$failed"

    if [ "$failed" -eq 0 ]; then
        printf "\n✓ All tests passed!\n"
        return 0
    else
        printf "\n✗ Some tests failed\n"
        return 1
    fi
}

# Run tests
run_all_tests
