#!/bin/sh
# Generated by Rash v0.3.1
# POSIX-compliant shell script

set -euf
IFS=' 	
'
export LC_ALL=C

# Rash runtime functions
rash_require() {
    if ! "$@"; then
        echo "FATAL: Requirement failed: $*" >&2
        exit 1
    fi
}

rash_download_verified() {
    url="$1"; dst="$2"; checksum="$3"
    
    if command -v curl >/dev/null 2>&1; then
        curl -fsSL --proto '=https' --tlsv1.2 "$url" -o "$dst"
    elif command -v wget >/dev/null 2>&1; then
        wget -qO "$dst" "$url"
    else
        echo "FATAL: Neither curl nor wget found" >&2
        return 1
    fi
    
    if command -v sha256sum >/dev/null 2>&1; then
        echo "$checksum  $dst" | sha256sum -c >/dev/null
    elif command -v shasum >/dev/null 2>&1; then
        echo "$checksum  $dst" | shasum -a 256 -c >/dev/null
    else
        echo "FATAL: No checksum utility found" >&2
        return 1
    fi
}

# Main script begins
main() {
    readonly message='Installation test successful'
    readonly version=1.0.0
}

# Cleanup on exit
trap 'rm -rf "${TMPDIR:-/tmp}/rash.$$"' EXIT

# Execute main function
main "$@"
