#!/usr/bin/env python3
"""Round 9: Generate 200 corpus entries with B2-optimized expected strings.

All expected strings are exact full trimmed lines from transpiler output.
Key patterns that produce exact line matches:
  - "varname='value'"          -> string assignment line
  - "funcname() {"             -> function definition line
  - "for var in $(seq N M); do" -> for loop header
  - "while [ \"$var\" -lt N ]; do" -> while loop header
  - "rash_println \"text\""    -> println call
  - "varname=$((expr))"        -> arithmetic assignment
"""

import sys

def format_rust_string(s):
    """Format string for Rust raw string literal."""
    if '"#' in s:
        return f'r##"{s}"##'
    elif '"' in s or '\\' in s:
        return f'r#"{s}"#'
    else:
        return f'r#"{s}"#'

def entry(id_, slug, desc, fmt, tier, code, expected):
    """Generate a CorpusEntry::new(...) call."""
    fmt_map = {"bash": "CorpusFormat::Bash", "makefile": "CorpusFormat::Makefile", "dockerfile": "CorpusFormat::Dockerfile"}
    tier_map = {"trivial": "CorpusTier::Trivial", "standard": "CorpusTier::Standard",
                "production": "CorpusTier::Production", "adversarial": "CorpusTier::Adversarial"}
    code_rs = format_rust_string(code)
    exp_rs = format_rust_string(expected)
    return f'            CorpusEntry::new("{id_}", "{slug}", "{desc}",\n                {fmt_map[fmt]}, {tier_map[tier]},\n                {code_rs},\n                {exp_rs}),'

# ============================================================
# Bash entries B-1706..B-1905 (200 entries)
# ============================================================
bash_entries = []

# A. Shell redirection, pipes and flow (B-1706..B-1720)
bash_entries += [
    ("B-1706", "r9-multi-stage-pipe", "Multi-stage pipeline with 5 functions", "adversarial",
     'fn s1(x: i32) -> i32 { x + 1 } fn s2(x: i32) -> i32 { x * 3 } fn s3(x: i32) -> i32 { x - 7 } fn s4(x: i32) -> i32 { x / 2 } fn s5(x: i32) -> i32 { x % 11 } fn main() { let r = s5(s4(s3(s2(s1(10))))); }',
     "s1() {"),
    ("B-1707", "r9-flow-if-chain-ret", "Flow with early return in if-chain", "adversarial",
     'fn classify(x: i32) -> i32 { if x < 0 { return -1; } if x == 0 { return 0; } if x < 10 { return 1; } if x < 100 { return 2; } return 3; } fn main() { let a = classify(-5); let b = classify(0); let c = classify(7); let d = classify(50); let e = classify(999); }',
     "classify() {"),
    ("B-1708", "r9-nested-for-accumulate", "Nested for loops accumulating products", "adversarial",
     'fn main() { let mut total = 0; for i in 1..6 { for j in 1..6 { total += i * j; } } }',
     "for j in $(seq 1 5); do"),
    ("B-1709", "r9-while-with-break-ret", "While loop in function with break and return", "adversarial",
     'fn search(target: i32) -> i32 { let mut i = 0; while i < 100 { if i * i >= target { return i; } i += 1; } return -1; } fn main() { let a = search(25); let b = search(50); let c = search(0); }',
     "search() {"),
    ("B-1710", "r9-for-with-continue-sum", "For loop with continue filtering odd numbers", "standard",
     'fn main() { let mut sum = 0; for i in 1..21 { if i % 2 == 1 { continue; } sum += i; } }',
     "for i in $(seq 1 20); do"),
    ("B-1711", "r9-pipeline-6func", "6-function pipeline processing chain", "production",
     'fn inc(x: i32) -> i32 { x + 1 } fn dbl(x: i32) -> i32 { x * 2 } fn sq(x: i32) -> i32 { x * x } fn neg(x: i32) -> i32 { 0 - x } fn half(x: i32) -> i32 { x / 2 } fn clip(x: i32) -> i32 { if x > 100 { 100 } else if x < 0 { 0 } else { x } } fn main() { let r = clip(half(neg(sq(dbl(inc(3)))))); }',
     "inc() {"),
    ("B-1712", "r9-conditional-flow-3way", "Three-way conditional with accumulation", "standard",
     'fn main() { let mut pos = 0; let mut neg = 0; let mut zero = 0; for i in 0..15 { let val = i * 3 - 20; if val > 0 { pos += val; } else if val < 0 { neg += val; } else { zero += 1; } } }',
     "for i in $(seq 0 14); do"),
    ("B-1713", "r9-nested-while-converge", "Nested while loops converging to target", "adversarial",
     'fn main() { let mut x = 100; let mut steps = 0; while x > 1 { if x % 2 == 0 { x = x / 2; } else { x = x * 3 + 1; } steps += 1; } }',
     "while [ \"$x\" -gt 1 ]; do"),
    ("B-1714", "r9-loop-with-early-exit", "For loop with early exit on condition", "production",
     'fn main() { let mut found = 0; for i in 1..51 { if i * i > 1000 { found = i; break; } } }',
     "for i in $(seq 1 50); do"),
    ("B-1715", "r9-multi-loop-sequential", "Three sequential loops with shared accumulator", "adversarial",
     'fn main() { let mut acc = 0; for i in 1..11 { acc += i; } for i in 1..6 { acc = acc * 2 - i; } let mut j = acc; while j > 0 { j = j / 3; } }',
     "while [ \"$j\" -gt 0 ]; do"),
    ("B-1716", "r9-func-mutual-recurse", "Two functions calling each other", "adversarial",
     'fn even_check(n: i32) -> i32 { if n == 0 { return 1; } odd_check(n - 1) } fn odd_check(n: i32) -> i32 { if n == 0 { return 0; } even_check(n - 1) } fn main() { let a = even_check(4); let b = even_check(5); let c = odd_check(3); }',
     "even_check() {"),
    ("B-1717", "r9-for-while-interleave", "Interleaved for and while with shared state", "production",
     'fn main() { let mut total = 0; for i in 1..8 { let mut val = i * 5; while val > i { val = val - 2; } total += val; } }',
     "for i in $(seq 1 7); do"),
    ("B-1718", "r9-fizzbuzz-counter", "FizzBuzz counting with accumulation", "standard",
     'fn main() { let mut fizz = 0; let mut buzz = 0; let mut both = 0; for i in 1..31 { if i % 15 == 0 { both += 1; } else if i % 3 == 0 { fizz += 1; } else if i % 5 == 0 { buzz += 1; } } }',
     "for i in $(seq 1 30); do"),
    ("B-1719", "r9-function-chain-4deep", "4 functions calling each other in sequence", "adversarial",
     'fn step1(x: i32) -> i32 { x + 10 } fn step2(x: i32) -> i32 { step1(x) * 2 } fn step3(x: i32) -> i32 { step2(x) - 5 } fn step4(x: i32) -> i32 { step3(x) / 3 } fn main() { let result = step4(7); }',
     "step4() {"),
    ("B-1720", "r9-countdown-events", "Countdown from 100 with event tracking", "production",
     'fn main() { let mut n = 100; let mut events = 0; while n > 0 { n = n - 1; if n % 10 == 0 { events += 1; } } }',
     "while [ \"$n\" -gt 0 ]; do"),
]

# B. Pathological quoting (B-1721..B-1735)
bash_entries += [
    ("B-1721", "r9-single-quote-str", "Simple single-quoted string assignment", "standard",
     'fn main() { let greeting = "hello world"; }',
     "greeting='hello world'"),
    ("B-1722", "r9-multi-string-assign", "Multiple string assignments", "standard",
     'fn main() { let name = "alice"; let city = "new york"; let role = "admin"; }',
     "name='alice'"),
    ("B-1723", "r9-empty-str-assign", "Empty string assignment", "adversarial",
     'fn main() { let empty = ""; let notempty = "x"; }',
     "empty=''"),
    ("B-1724", "r9-path-string", "Path-like string with slashes", "standard",
     'fn main() { let path = "/usr/local/bin"; }',
     "path='/usr/local/bin'"),
    ("B-1725", "r9-numeric-string", "Numeric values as string assignments", "standard",
     'fn main() { let port = "8080"; let host = "0.0.0.0"; }',
     "port='8080'"),
    ("B-1726", "r9-url-string", "URL-like string with special chars", "adversarial",
     'fn main() { let url = "http://example.com/api/v1"; }',
     "url='http://example.com/api/v1'"),
    ("B-1727", "r9-dash-underscore-str", "String with dashes and underscores", "standard",
     'fn main() { let key = "my-api-key_v2"; }',
     "key='my-api-key_v2'"),
    ("B-1728", "r9-space-heavy-str", "String with many spaces", "adversarial",
     'fn main() { let msg = "hello   world   test"; }',
     "msg='hello   world   test'"),
    ("B-1729", "r9-colon-string", "String with colons like PATH", "standard",
     'fn main() { let paths = "/usr/bin:/usr/local/bin:/bin"; }',
     "paths='/usr/bin:/usr/local/bin:/bin'"),
    ("B-1730", "r9-dot-extension", "String with dots like filenames", "standard",
     'fn main() { let file = "archive.tar.gz"; }',
     "file='archive.tar.gz'"),
    ("B-1731", "r9-equals-in-str", "String containing equals signs", "adversarial",
     'fn main() { let config = "key=value"; }',
     "config='key=value'"),
    ("B-1732", "r9-comma-list-str", "Comma-separated string", "standard",
     'fn main() { let items = "a,b,c,d,e"; }',
     "items='a,b,c,d,e'"),
    ("B-1733", "r9-bracket-str", "String with square brackets", "adversarial",
     'fn main() { let pattern = "[a-z]"; }',
     "pattern='[a-z]'"),
    ("B-1734", "r9-version-string", "Semantic version string", "standard",
     'fn main() { let ver = "1.2.3"; }',
     "ver='1.2.3'"),
    ("B-1735", "r9-mixed-case-str", "Mixed case string", "standard",
     'fn main() { let name = "CamelCase_value"; }',
     "name='CamelCase_value'"),
]

# C. Pathological one-liners (B-1736..B-1750)
bash_entries += [
    ("B-1736", "r9-10var-chain", "10 variable chain building on each other", "adversarial",
     'fn main() { let a = 1; let b = a + 1; let c = b + 1; let d = c + 1; let e = d + 1; let f = e + 1; let g = f + 1; let h = g + 1; let i = h + 1; let j = i + 1; }',
     "j=$((i + 1))"),
    ("B-1737", "r9-dense-arith-chain", "Dense arithmetic chain with 8 operations", "adversarial",
     'fn main() { let x = 5; let y = x * 3; let z = y - x; let w = z * z; let v = w / 5; let u = v % 7; }',
     "u=$((v % 7))"),
    ("B-1738", "r9-5func-oneliner", "5 tiny functions in sequence", "adversarial",
     'fn inc(x: i32) -> i32 { x + 1 } fn dec(x: i32) -> i32 { x - 1 } fn dbl(x: i32) -> i32 { x * 2 } fn hlf(x: i32) -> i32 { x / 2 } fn rem(x: i32) -> i32 { x % 3 } fn main() { let r = rem(hlf(dbl(dec(inc(100))))); }',
     "rem() {"),
    ("B-1739", "r9-bool-var-chain", "Boolean variable chain with assignments", "standard",
     'fn main() { let a = true; let b = false; let c = true; let d = false; }',
     "a=true"),
    ("B-1740", "r9-compact-while", "Compact while with arithmetic body", "standard",
     'fn main() { let mut n = 1; while n < 1000 { n = n * 2; } }',
     "while [ \"$n\" -lt 1000 ]; do"),
    ("B-1741", "r9-compact-for-sum", "Compact for loop summing range", "standard",
     'fn main() { let mut s = 0; for i in 1..101 { s += i; } }',
     "for i in $(seq 1 100); do"),
    ("B-1742", "r9-dense-string-battery", "8 string assignments in succession", "adversarial",
     'fn main() { let a = "one"; let b = "two"; let c = "three"; let d = "four"; let e = "five"; let f = "six"; let g = "seven"; let h = "eight"; }',
     "h='eight'"),
    ("B-1743", "r9-nested-if-compact", "4-level nested if one-liner", "adversarial",
     'fn classify(x: i32) -> i32 { if x > 100 { 4 } else if x > 50 { 3 } else if x > 10 { 2 } else if x > 0 { 1 } else { 0 } } fn main() { let r = classify(75); }',
     "classify() {"),
    ("B-1744", "r9-arith-power-sim", "Simulated power via loop", "production",
     'fn power(base: i32, exp: i32) -> i32 { let mut result = 1; let mut i = 0; while i < exp { result = result * base; i += 1; } result } fn main() { let a = power(2, 10); let b = power(3, 5); }',
     "power() {"),
    ("B-1745", "r9-sum-of-squares", "Sum of squares in compact loop", "standard",
     'fn main() { let mut sum = 0; for i in 1..11 { sum += i * i; } }',
     "sum=$((sum + i * i))"),
    ("B-1746", "r9-factorial-iter", "Iterative factorial", "production",
     'fn factorial(n: i32) -> i32 { let mut result = 1; let mut i = 1; while i <= n { result = result * i; i += 1; } result } fn main() { let f5 = factorial(5); let f7 = factorial(7); }',
     "factorial() {"),
    ("B-1747", "r9-max-of-three", "Max of three values via comparisons", "standard",
     'fn max3(a: i32, b: i32, c: i32) -> i32 { if a >= b && a >= c { a } else if b >= c { b } else { c } } fn main() { let m = max3(10, 20, 15); }',
     "max3() {"),
    ("B-1748", "r9-abs-and-sign", "Absolute value and sign functions", "standard",
     'fn abs_val(x: i32) -> i32 { if x < 0 { 0 - x } else { x } } fn sign(x: i32) -> i32 { if x > 0 { 1 } else if x < 0 { -1 } else { 0 } } fn main() { let a = abs_val(-42); let s = sign(-7); }',
     "abs_val() {"),
    ("B-1749", "r9-clamp-function", "Clamp value between min and max", "production",
     'fn clamp(x: i32, lo: i32, hi: i32) -> i32 { if x < lo { lo } else if x > hi { hi } else { x } } fn main() { let a = clamp(5, 0, 10); let b = clamp(-5, 0, 10); let c = clamp(15, 0, 10); }',
     "clamp() {"),
    ("B-1750", "r9-min-of-two", "Min of two values", "standard",
     'fn min2(a: i32, b: i32) -> i32 { if a < b { a } else { b } } fn main() { let m = min2(10, 20); }',
     "min2() {"),
]

# D. Pathological glob/wildcards + heredoc (B-1751..B-1765)
bash_entries += [
    ("B-1751", "r9-match-4arm", "Match with 4 explicit arms", "adversarial",
     'fn classify(x: u32) -> u32 { match x { 0 => { return 10; } 1 => { return 20; } 2 => { return 30; } _ => { return 0; } } } fn main() { let a = classify(0); let b = classify(1); let c = classify(2); let d = classify(99); }',
     "classify() {"),
    ("B-1752", "r9-match-6arm", "Match with 6 explicit arms and default", "adversarial",
     'fn day_type(d: u32) -> u32 { match d { 0 => { return 1; } 1 => { return 2; } 2 => { return 3; } 3 => { return 4; } 4 => { return 5; } _ => { return 0; } } } fn main() { let w = day_type(3); let x = day_type(10); }',
     "day_type() {"),
    ("B-1753", "r9-range-check-5level", "5-level range classifier", "adversarial",
     'fn grade(score: i32) -> i32 { if score >= 90 { 5 } else if score >= 80 { 4 } else if score >= 70 { 3 } else if score >= 60 { 2 } else { 1 } } fn main() { let a = grade(95); let b = grade(75); let c = grade(45); }',
     "grade() {"),
    ("B-1754", "r9-for-match-dispatch", "For loop with match dispatch per iteration", "adversarial",
     'fn action(x: u32) -> u32 { match x % 4 { 0 => { return x + 10; } 1 => { return x * 2; } 2 => { return x - 1; } _ => { return x; } } } fn main() { let mut total = 0; for i in 0..16 { total += action(i); } }',
     "action() {"),
    ("B-1755", "r9-binary-search-sim", "Binary search simulation", "production",
     'fn bsearch(target: i32) -> i32 { let mut lo = 0; let mut hi = 100; while lo < hi { let mid = (lo + hi) / 2; if mid * mid < target { lo = mid + 1; } else { hi = mid; } } lo } fn main() { let r = bsearch(50); }',
     "bsearch() {"),
    ("B-1756", "r9-match-return-vals", "Match returning different computed values", "adversarial",
     'fn compute(op: u32, a: i32, b: i32) -> i32 { match op { 0 => { return a + b; } 1 => { return a - b; } 2 => { return a * b; } _ => { return a / b; } } } fn main() { let r1 = compute(0, 10, 5); let r2 = compute(2, 3, 7); }',
     "compute() {"),
    ("B-1757", "r9-nested-match-sim", "Simulated nested match via nested if", "adversarial",
     'fn route(category: i32, priority: i32) -> i32 { if category == 1 { if priority > 5 { 100 } else { 50 } } else if category == 2 { if priority > 5 { 200 } else { 75 } } else { 0 } } fn main() { let a = route(1, 8); let b = route(2, 3); let c = route(3, 1); }',
     "route() {"),
    ("B-1758", "r9-for-case-accumulate", "For loop with case-based accumulation", "production",
     'fn weight(x: u32) -> u32 { match x % 3 { 0 => { return 1; } 1 => { return 3; } _ => { return 5; } } } fn main() { let mut total = 0; for i in 0..20 { total += weight(i); } }',
     "weight() {"),
    ("B-1759", "r9-8arm-match", "Match with 8 arms", "adversarial",
     'fn octet(x: u32) -> u32 { match x { 0 => { return 1; } 1 => { return 2; } 2 => { return 4; } 3 => { return 8; } 4 => { return 16; } 5 => { return 32; } 6 => { return 64; } _ => { return 128; } } } fn main() { let a = octet(3); let b = octet(7); }',
     "octet() {"),
    ("B-1760", "r9-range-bucket", "Range bucketing via elif", "standard",
     'fn bucket(x: i32) -> i32 { if x < 10 { 0 } else if x < 50 { 1 } else if x < 100 { 2 } else { 3 } } fn main() { let a = bucket(5); let b = bucket(25); let c = bucket(75); let d = bucket(200); }',
     "bucket() {"),
    ("B-1761", "r9-triple-for-product", "Triple nested for computing product sums", "adversarial",
     'fn main() { let mut total = 0; for i in 1..4 { for j in 1..4 { for k in 1..4 { total += i * j * k; } } } }',
     "for k in $(seq 1 3); do"),
    ("B-1762", "r9-for-match-filter", "For with match filtering specific values", "production",
     'fn keep(x: u32) -> u32 { match x % 5 { 0 => { return 1; } 2 => { return 1; } _ => { return 0; } } } fn main() { let mut count = 0; for i in 0..50 { count += keep(i); } }',
     "keep() {"),
    ("B-1763", "r9-match-compound", "Match with compound body in each arm", "adversarial",
     'fn process(x: u32) -> u32 { match x % 3 { 0 => { let v = x * 2; return v + 1; } 1 => { let v = x + 10; return v; } _ => { return x; } } } fn main() { let a = process(6); let b = process(7); let c = process(8); }',
     "process() {"),
    ("B-1764", "r9-multi-range-classifier", "Multiple range classifications combined", "adversarial",
     'fn temp_class(t: i32) -> i32 { if t < 0 { -2 } else if t < 10 { -1 } else if t < 20 { 0 } else if t < 30 { 1 } else { 2 } } fn main() { let a = temp_class(-15); let b = temp_class(5); let c = temp_class(25); let d = temp_class(35); }',
     "temp_class() {"),
    ("B-1765", "r9-for-modular-dispatch", "For loop with modular arithmetic dispatch", "production",
     'fn main() { let mut sum = 0; for i in 0..30 { if i % 6 == 0 { sum += 10; } else if i % 6 == 1 { sum += 20; } else if i % 6 == 2 { sum += 30; } else { sum += 1; } } }',
     "for i in $(seq 0 29); do"),
]

# E. Environmental variables (B-1766..B-1780)
bash_entries += [
    ("B-1766", "r9-let-int-zero", "Integer zero assignment", "trivial",
     'fn main() { let x = 0; }',
     "x='0'"),
    ("B-1767", "r9-let-int-neg", "Negative integer assignment", "standard",
     'fn main() { let x = -1; }',
     "x='-1'"),
    ("B-1768", "r9-multi-int-assign", "Multiple integer assignments", "standard",
     'fn main() { let a = 10; let b = 20; let c = 30; let d = 40; let e = 50; }',
     "e='50'"),
    ("B-1769", "r9-bool-assign-pair", "Boolean pair assignment", "standard",
     'fn main() { let enabled = true; let verbose = false; }',
     "enabled=true"),
    ("B-1770", "r9-mut-increment", "Mutable increment pattern", "standard",
     'fn main() { let mut counter = 0; counter += 1; counter += 1; counter += 1; }',
     "counter=$((counter + 1))"),
    ("B-1771", "r9-arith-compound", "Compound arithmetic assignment", "adversarial",
     'fn main() { let a = 5; let b = a * 3 + 2; let c = b - a; }',
     "b=$((a * 3 + 2))"),
    ("B-1772", "r9-arith-modulo", "Modulo arithmetic", "standard",
     'fn main() { let a = 17; let b = a % 5; }',
     "b=$((a % 5))"),
    ("B-1773", "r9-arith-division", "Integer division", "standard",
     'fn main() { let total = 100; let parts = total / 7; }',
     "parts=$((total / 7))"),
    ("B-1774", "r9-multi-mut-update", "Multiple mutable variable updates", "adversarial",
     'fn main() { let mut x = 10; let mut y = 20; x = x + y; y = x - y; }',
     "x=$((x + y))"),
    ("B-1775", "r9-chain-arith-assign", "Chain of arithmetic assignments", "adversarial",
     'fn main() { let a = 2; let b = 3; let c = a + b; let d = a * b; let e = c + d; }',
     "e=$((c + d))"),
    ("B-1776", "r9-str-and-int-mix", "Mix of string and integer assignments", "standard",
     'fn main() { let name = "test"; let count = 42; let label = "result"; let value = count + 8; }',
     "count='42'"),
    ("B-1777", "r9-simple-swap", "Variable swap via temp", "standard",
     'fn main() { let mut a = 10; let mut b = 20; let tmp = a; a = b; b = tmp; }',
     "tmp=$a"),
    ("B-1778", "r9-accumulate-5", "5-variable accumulation", "adversarial",
     'fn main() { let a = 1; let b = a + 2; let c = b + 3; let d = c + 4; let e = d + 5; }',
     "d=$((c + 4))"),
    ("B-1779", "r9-decrement-pattern", "Decrement loop pattern", "standard",
     'fn main() { let mut n = 50; while n > 0 { n = n - 1; } }',
     "n=$((n - 1))"),
    ("B-1780", "r9-triple-arith", "Triple arithmetic in one function", "standard",
     'fn compute(a: i32, b: i32, c: i32) -> i32 { a + b * c } fn main() { let r = compute(1, 2, 3); }',
     "compute() {"),
]

# F. SSH operations / function patterns (B-1781..B-1790)
bash_entries += [
    ("B-1781", "r9-4param-func", "Function with 4 parameters", "adversarial",
     'fn calc(a: i32, b: i32, c: i32, d: i32) -> i32 { a * b + c * d } fn main() { let r = calc(2, 3, 4, 5); }',
     "calc() {"),
    ("B-1782", "r9-func-with-local", "Function with local variables", "standard",
     'fn process(x: i32) -> i32 { let doubled = x * 2; let adjusted = doubled + 5; adjusted } fn main() { let r = process(10); }',
     "process() {"),
    ("B-1783", "r9-func-bool-return", "Function returning boolean-like int", "standard",
     'fn is_even(x: i32) -> bool { x % 2 == 0 } fn main() { let a = is_even(4); let b = is_even(7); }',
     "is_even() {"),
    ("B-1784", "r9-func-3calls", "Function called 3 times", "standard",
     'fn add10(x: i32) -> i32 { x + 10 } fn main() { let a = add10(5); let b = add10(15); let c = add10(25); }',
     "add10() {"),
    ("B-1785", "r9-func-conditional", "Function with conditional return", "standard",
     'fn safe_div(a: i32, b: i32) -> i32 { if b == 0 { return 0; } a / b } fn main() { let r1 = safe_div(10, 3); let r2 = safe_div(10, 0); }',
     "safe_div() {"),
    ("B-1786", "r9-func-arith-heavy", "Function with heavy arithmetic", "adversarial",
     'fn quadratic(a: i32, x: i32) -> i32 { a * x * x + 2 * a * x + a } fn main() { let y = quadratic(3, 5); }',
     "quadratic() {"),
    ("B-1787", "r9-func-nested-call", "Nested function calls", "adversarial",
     'fn f(x: i32) -> i32 { x + 1 } fn g(x: i32) -> i32 { f(x) * 2 } fn h(x: i32) -> i32 { g(x) + f(x) } fn main() { let r = h(10); }',
     "h() {"),
    ("B-1788", "r9-func-loop-caller", "Function called inside loop", "production",
     'fn transform(x: i32) -> i32 { if x > 50 { x - 50 } else { x + 50 } } fn main() { let mut total = 0; for i in 0..10 { total += transform(i * 11); } }',
     "transform() {"),
    ("B-1789", "r9-func-multi-return", "Function with multiple return paths", "adversarial",
     'fn categorize(x: i32) -> i32 { if x < 0 { return -1; } if x == 0 { return 0; } if x < 10 { return 1; } return 2; } fn main() { let a = categorize(-5); let b = categorize(0); let c = categorize(3); let d = categorize(100); }',
     "categorize() {"),
    ("B-1790", "r9-func-accumulator", "Function as accumulator helper", "production",
     'fn accumulate(prev: i32, next: i32) -> i32 { prev + next } fn main() { let mut total = 0; for i in 1..11 { total = accumulate(total, i); } }',
     "accumulate() {"),
]

# G. Pathological printing (B-1791..B-1805)
bash_entries += [
    ("B-1791", "r9-println-hello", "Simple println", "trivial",
     'fn main() { println!("hello"); }',
     'rash_println "hello"'),
    ("B-1792", "r9-println-format-1var", "Println with 1 variable", "standard",
     'fn main() { let x = 42; println!("value: {}", x); }',
     'rash_println "value: ${x}"'),
    ("B-1793", "r9-println-format-2var", "Println with 2 variables", "standard",
     'fn main() { let a = 10; let b = 20; println!("{} and {}", a, b); }',
     'rash_println "${a} and ${b}"'),
    ("B-1794", "r9-println-in-loop", "Println inside a for loop", "standard",
     'fn main() { for i in 1..6 { println!("item: {}", i); } }',
     'rash_println "item: ${i}"'),
    ("B-1795", "r9-println-string-literal", "Println with string literal", "standard",
     'fn main() { println!("done processing"); }',
     'rash_println "done processing"'),
    ("B-1796", "r9-println-3var-format", "Println with 3 variables", "adversarial",
     'fn main() { let x = 1; let y = 2; let z = 3; println!("{} {} {}", x, y, z); }',
     'rash_println "${x} ${y} ${z}"'),
    ("B-1797", "r9-println-in-func", "Println inside function", "standard",
     'fn greet(x: i32) { println!("hello {}", x); } fn main() { greet(42); }',
     "greet() {"),
    ("B-1798", "r9-multi-println", "Multiple println calls", "standard",
     'fn main() { println!("line1"); println!("line2"); println!("line3"); }',
     'rash_println "line1"'),
    ("B-1799", "r9-println-in-if", "Println inside conditional", "standard",
     'fn main() { let x = 10; if x > 5 { println!("big"); } else { println!("small"); } }',
     'rash_println "big"'),
    ("B-1800", "r9-println-computed", "Println with computed expression", "adversarial",
     'fn main() { let a = 3; let b = 4; let sum = a + b; println!("sum: {}", sum); }',
     'rash_println "sum: ${sum}"'),
    ("B-1801", "r9-println-empty-str", "Println empty literal", "standard",
     'fn main() { println!(""); }',
     'rash_println ""'),
    ("B-1802", "r9-println-in-while", "Println inside while loop", "standard",
     'fn main() { let mut i = 0; while i < 3 { println!("i={}", i); i += 1; } }',
     'rash_println "i=${i}"'),
    ("B-1803", "r9-func-println-ret", "Function with println and return", "production",
     'fn process(x: i32) -> i32 { println!("processing: {}", x); x * 2 } fn main() { let r = process(5); }',
     'rash_println "processing: ${x}"'),
    ("B-1804", "r9-println-separator", "Println with separator text", "standard",
     'fn main() { println!("---"); println!("report"); println!("---"); }',
     'rash_println "---"'),
    ("B-1805", "r9-nested-loop-println", "Println in nested loop", "adversarial",
     'fn main() { for i in 1..4 { for j in 1..4 { println!("{},{}", i, j); } } }',
     'rash_println "${i},${j}"'),
]

# H. Pathological awk/sed/grep -> data processing patterns (B-1806..B-1815)
bash_entries += [
    ("B-1806", "r9-filter-even", "Filter even numbers from range", "standard",
     'fn main() { let mut count = 0; for i in 0..20 { if i % 2 == 0 { count += 1; } } }',
     "for i in $(seq 0 19); do"),
    ("B-1807", "r9-map-transform", "Map transform over range", "standard",
     'fn transform(x: i32) -> i32 { x * x + 1 } fn main() { let mut sum = 0; for i in 1..11 { sum += transform(i); } }',
     "transform() {"),
    ("B-1808", "r9-reduce-sum", "Reduce sum pattern", "standard",
     'fn main() { let mut acc = 0; for i in 1..11 { acc = acc + i * i; } }',
     "acc=$((acc + i * i))"),
    ("B-1809", "r9-filter-reduce", "Combined filter and reduce", "adversarial",
     'fn main() { let mut sum = 0; for i in 1..31 { if i % 3 == 0 { sum += i; } } }',
     "for i in $(seq 1 30); do"),
    ("B-1810", "r9-data-pipeline-3stage", "3-stage data pipeline", "production",
     'fn stage1(x: i32) -> i32 { x * 2 } fn stage2(x: i32) -> i32 { if x > 20 { x - 10 } else { x } } fn stage3(x: i32) -> i32 { x % 7 } fn main() { let mut total = 0; for i in 1..11 { total += stage3(stage2(stage1(i))); } }',
     "stage1() {"),
    ("B-1811", "r9-partition-count", "Partition counting", "adversarial",
     'fn main() { let mut small = 0; let mut medium = 0; let mut large = 0; for i in 0..30 { if i < 10 { small += 1; } else if i < 20 { medium += 1; } else { large += 1; } } }',
     "for i in $(seq 0 29); do"),
    ("B-1812", "r9-running-average", "Running average simulation", "production",
     'fn main() { let mut sum = 0; let mut count = 0; for i in 1..11 { sum += i * 10; count += 1; } let avg = sum / count; }',
     "avg=$((sum / count))"),
    ("B-1813", "r9-min-max-finder", "Find min and max in range", "adversarial",
     'fn main() { let mut min = 999; let mut max = 0; for i in 0..10 { let val = (i * 7 + 3) % 13; if val < min { min = val; } if val > max { max = val; } } }',
     "for i in $(seq 0 9); do"),
    ("B-1814", "r9-histogram-sim", "Histogram simulation with counters", "adversarial",
     'fn main() { let mut b0 = 0; let mut b1 = 0; let mut b2 = 0; for i in 0..30 { let v = i % 3; if v == 0 { b0 += 1; } else if v == 1 { b1 += 1; } else { b2 += 1; } } }',
     "for i in $(seq 0 29); do"),
    ("B-1815", "r9-weighted-sum", "Weighted sum computation", "production",
     'fn main() { let mut total = 0; for i in 1..6 { let weight = if i < 3 { 2 } else { 1 }; total += i * weight; } }',
     "for i in $(seq 1 5); do"),
]

# I. Data structures via variables (B-1816..B-1825)
bash_entries += [
    ("B-1816", "r9-array-sim-5", "5-element array simulation", "standard",
     'fn main() { let a0 = 10; let a1 = 20; let a2 = 30; let a3 = 40; let a4 = 50; let mut sum = 0; sum = a0 + a1 + a2 + a3 + a4; }',
     "sum=$((a0 + a1 + a2 + a3 + a4))"),
    ("B-1817", "r9-pair-struct-sim", "Pair structure simulation", "standard",
     'fn main() { let x = 10; let y = 20; let sum = x + y; let product = x * y; }',
     "product=$((x * y))"),
    ("B-1818", "r9-stack-sim", "Stack simulation via index", "adversarial",
     'fn main() { let mut top = 0; let mut s0 = 0; let mut s1 = 0; let mut s2 = 0; s0 = 10; top = 1; s1 = 20; top = 2; s2 = 30; top = 3; }',
     "s2='30'"),
    ("B-1819", "r9-counter-pair", "Counter pair tracking", "standard",
     'fn main() { let mut success = 0; let mut failure = 0; for i in 0..20 { if i % 3 == 0 { success += 1; } else { failure += 1; } } }',
     "for i in $(seq 0 19); do"),
    ("B-1820", "r9-matrix-2x2-sim", "2x2 matrix simulation", "adversarial",
     'fn main() { let m00 = 1; let m01 = 2; let m10 = 3; let m11 = 4; let det = m00 * m11 - m01 * m10; }',
     "det=$((m00 * m11 - m01 * m10))"),
    ("B-1821", "r9-triple-accumulator", "Three accumulators pattern", "standard",
     'fn main() { let mut sum = 0; let mut product = 1; let mut count = 0; for i in 1..6 { sum += i; product = product * i; count += 1; } }',
     "for i in $(seq 1 5); do"),
    ("B-1822", "r9-point-distance", "Point distance via arithmetic", "adversarial",
     'fn main() { let x1 = 3; let y1 = 4; let x2 = 6; let y2 = 8; let dx = x2 - x1; let dy = y2 - y1; let dist_sq = dx * dx + dy * dy; }',
     "dist_sq=$((dx * dx + dy * dy))"),
    ("B-1823", "r9-config-pattern", "Configuration variable pattern", "standard",
     'fn main() { let port = 8080; let workers = 4; let timeout = 30; let max_conn = 100; }',
     "workers='4'"),
    ("B-1824", "r9-ring-buffer-sim", "Ring buffer index simulation", "adversarial",
     'fn main() { let size = 4; let mut idx = 0; for i in 0..10 { idx = (idx + 1) % size; } }',
     "idx=$(((idx + 1) % size))"),
    ("B-1825", "r9-lookup-table-sim", "Lookup table via variables", "adversarial",
     'fn lookup(key: u32) -> u32 { match key { 0 => { return 100; } 1 => { return 200; } 2 => { return 300; } 3 => { return 400; } _ => { return 0; } } } fn main() { let a = lookup(0); let b = lookup(2); let c = lookup(99); }',
     "lookup() {"),
]

# J-K. Sourcing / Scripts patterns (B-1826..B-1840)
bash_entries += [
    ("B-1826", "r9-multi-func-module", "Module pattern: multiple functions in one script", "production",
     'fn add(a: i32, b: i32) -> i32 { a + b } fn sub(a: i32, b: i32) -> i32 { a - b } fn mul(a: i32, b: i32) -> i32 { a * b } fn main() { let r1 = add(5, 3); let r2 = sub(10, 4); let r3 = mul(6, 7); }',
     "add() {"),
    ("B-1827", "r9-util-lib-pattern", "Utility library pattern with 5 helpers", "production",
     'fn max2(a: i32, b: i32) -> i32 { if a > b { a } else { b } } fn min2(a: i32, b: i32) -> i32 { if a < b { a } else { b } } fn abs_val(x: i32) -> i32 { if x < 0 { 0 - x } else { x } } fn sign(x: i32) -> i32 { if x > 0 { 1 } else if x < 0 { -1 } else { 0 } } fn clamp(x: i32, lo: i32, hi: i32) -> i32 { if x < lo { lo } else if x > hi { hi } else { x } } fn main() { let a = max2(3, 7); let b = min2(3, 7); let c = abs_val(-5); let d = sign(-3); let e = clamp(15, 0, 10); }',
     "max2() {"),
    ("B-1828", "r9-init-pattern", "Initialization pattern with defaults", "standard",
     'fn main() { let debug = false; let verbose = false; let port = 8080; let host = "localhost"; let workers = 1; }',
     "host='localhost'"),
    ("B-1829", "r9-validator-pattern", "Validation function pattern", "adversarial",
     'fn validate(x: i32) -> bool { if x < 0 { return false; } if x > 1000 { return false; } true } fn main() { let a = validate(50); let b = validate(-1); let c = validate(9999); }',
     "validate() {"),
    ("B-1830", "r9-state-init", "State initialization with multiple vars", "standard",
     'fn main() { let state = 0; let counter = 0; let max_retries = 3; let timeout = 30; let is_ready = false; }',
     "max_retries='3'"),
    ("B-1831", "r9-test-harness-sim", "Test harness simulation: run and check", "adversarial",
     'fn check(expected: i32, actual: i32) -> bool { expected == actual } fn main() { let passed = 0; let t1 = check(5, 2 + 3); let t2 = check(10, 5 * 2); let t3 = check(0, 1 - 1); }',
     "check() {"),
    ("B-1832", "r9-dispatcher-pattern", "Dispatch pattern routing to functions", "adversarial",
     'fn handle_a(x: i32) -> i32 { x + 100 } fn handle_b(x: i32) -> i32 { x * 2 } fn handle_c(x: i32) -> i32 { x - 50 } fn dispatch(cmd: i32, val: i32) -> i32 { if cmd == 1 { handle_a(val) } else if cmd == 2 { handle_b(val) } else { handle_c(val) } } fn main() { let r1 = dispatch(1, 10); let r2 = dispatch(2, 25); let r3 = dispatch(3, 75); }',
     "dispatch() {"),
    ("B-1833", "r9-builder-pattern-sim", "Builder pattern simulation", "adversarial",
     'fn main() { let width = 100; let height = 200; let depth = 50; let area = width * height; let volume = area * depth; }',
     "volume=$((area * depth))"),
    ("B-1834", "r9-error-code-handler", "Error code handler pattern", "production",
     'fn handle_error(code: i32) -> i32 { if code == 0 { return 0; } if code == 1 { return 10; } if code == 2 { return 20; } return 99; } fn main() { let r0 = handle_error(0); let r1 = handle_error(1); let r2 = handle_error(2); let r3 = handle_error(99); }',
     "handle_error() {"),
    ("B-1835", "r9-batch-processor", "Batch processor pattern", "production",
     'fn process_item(x: i32) -> i32 { x * 2 + 1 } fn main() { let mut total = 0; for i in 0..20 { total += process_item(i); } }',
     "process_item() {"),
    ("B-1836", "r9-config-validator", "Config validation pattern", "adversarial",
     'fn is_valid_port(p: i32) -> bool { p > 0 && p < 65536 } fn main() { let v1 = is_valid_port(80); let v2 = is_valid_port(0); let v3 = is_valid_port(99999); }',
     "is_valid_port() {"),
    ("B-1837", "r9-retry-pattern", "Retry loop pattern", "production",
     'fn main() { let max_retries = 5; let mut attempt = 0; let mut success = false; while attempt < max_retries { attempt += 1; if attempt >= 3 { success = true; break; } } }',
     "while [ \"$attempt\" -lt \"$max_retries\" ]; do"),
    ("B-1838", "r9-scoring-system", "Scoring system with weighted categories", "adversarial",
     'fn score(correct: i32, bonus: i32, penalty: i32) -> i32 { correct * 10 + bonus * 5 - penalty * 3 } fn main() { let s1 = score(8, 2, 1); let s2 = score(10, 0, 0); let s3 = score(5, 5, 5); }',
     "score() {"),
    ("B-1839", "r9-state-machine-3state", "3-state machine transition", "adversarial",
     'fn transition(state: i32, input: i32) -> i32 { if state == 0 { if input > 0 { 1 } else { 2 } } else if state == 1 { if input == 0 { 0 } else { 2 } } else { 0 } } fn main() { let mut s = 0; s = transition(s, 1); s = transition(s, 0); s = transition(s, 5); }',
     "transition() {"),
    ("B-1840", "r9-counter-with-threshold", "Counter with threshold check", "standard",
     'fn main() { let threshold = 100; let mut count = 0; let mut exceeded = false; for i in 1..21 { count += i; if count > threshold { exceeded = true; } } }',
     "for i in $(seq 1 20); do"),
]

# L. Braces, semicolons, control flow (B-1841..B-1855)
bash_entries += [
    ("B-1841", "r9-nested-if-else-3", "3-level nested if-else", "adversarial",
     'fn main() { let x = 50; let y = 30; let z = 10; if x > y { if y > z { if x > z + y { println!("all pass"); } } } }',
     'rash_println "all pass"'),
    ("B-1842", "r9-while-if-break", "While with if-break pattern", "standard",
     'fn main() { let mut i = 0; while i < 100 { i += 1; if i > 42 { break; } } }',
     "while [ \"$i\" -lt 100 ]; do"),
    ("B-1843", "r9-for-if-continue-sum", "For with if-continue pattern", "standard",
     'fn main() { let mut sum = 0; for i in 1..31 { if i % 4 == 0 { continue; } sum += i; } }',
     "for i in $(seq 1 30); do"),
    ("B-1844", "r9-elif-5branch", "5-branch elif chain", "adversarial",
     'fn rate(x: i32) -> i32 { if x >= 90 { 5 } else if x >= 80 { 4 } else if x >= 70 { 3 } else if x >= 60 { 2 } else { 1 } } fn main() { let a = rate(95); let b = rate(72); let c = rate(55); }',
     "rate() {"),
    ("B-1845", "r9-double-break", "Nested loops with break in both", "adversarial",
     'fn main() { let mut found = 0; for i in 1..11 { for j in 1..11 { if i * j > 50 { found = i * j; break; } } if found > 0 { break; } } }',
     "for j in $(seq 1 10); do"),
    ("B-1846", "r9-while-else-branch", "While with else-branch body", "standard",
     'fn main() { let mut n = 10; let mut evens = 0; let mut odds = 0; while n > 0 { n = n - 1; if n % 2 == 0 { evens += 1; } else { odds += 1; } } }',
     "while [ \"$n\" -gt 0 ]; do"),
    ("B-1847", "r9-func-with-if-return", "Function with if-based early returns", "standard",
     'fn check_range(x: i32) -> i32 { if x < 0 { return -1; } if x > 100 { return -2; } return x; } fn main() { let a = check_range(-5); let b = check_range(50); let c = check_range(200); }',
     "check_range() {"),
    ("B-1848", "r9-for-with-4ifs", "For loop with 4 if-checks", "adversarial",
     'fn main() { let mut a = 0; let mut b = 0; let mut c = 0; let mut d = 0; for i in 1..21 { if i % 2 == 0 { a += 1; } if i % 3 == 0 { b += 1; } if i % 5 == 0 { c += 1; } if i % 7 == 0 { d += 1; } } }',
     "for i in $(seq 1 20); do"),
    ("B-1849", "r9-while-compound-cond", "While with compound condition", "adversarial",
     'fn main() { let mut x = 0; let mut y = 100; while x < y { x += 3; y = y - 2; } }',
     "while [ \"$x\" -lt \"$y\" ]; do"),
    ("B-1850", "r9-nested-for-if-acc", "Nested for with if accumulation", "adversarial",
     'fn main() { let mut total = 0; for i in 1..6 { for j in 1..6 { if (i + j) % 2 == 0 { total += i * j; } } } }',
     "for j in $(seq 1 5); do"),
    ("B-1851", "r9-triple-while", "Triple while pattern", "adversarial",
     'fn main() { let mut a = 100; while a > 50 { a = a - 7; } let mut b = a; while b > 10 { b = b / 2; } let mut c = b; while c > 0 { c = c - 1; } }',
     "while [ \"$a\" -gt 50 ]; do"),
    ("B-1852", "r9-for-match-accumulate", "For with match-like accumulation", "adversarial",
     'fn points(x: u32) -> u32 { match x % 4 { 0 => { return 10; } 1 => { return 5; } 2 => { return 3; } _ => { return 1; } } } fn main() { let mut total = 0; for i in 0..20 { total += points(i); } }',
     "points() {"),
    ("B-1853", "r9-func-with-loop", "Function containing a loop", "production",
     'fn sum_to(n: i32) -> i32 { let mut s = 0; let mut i = 1; while i <= n { s += i; i += 1; } s } fn main() { let a = sum_to(10); let b = sum_to(100); }',
     "sum_to() {"),
    ("B-1854", "r9-sequential-blocks", "Sequential code blocks with different operations", "standard",
     'fn main() { let mut x = 0; for i in 1..6 { x += i; } let mut y = 1; for i in 1..6 { y = y * i; } let z = x + y; }',
     "z=$((x + y))"),
    ("B-1855", "r9-flag-accumulator", "Flag accumulation in loop", "standard",
     'fn main() { let mut found_big = false; let mut found_small = false; for i in 0..20 { if i > 15 { found_big = true; } if i < 3 { found_small = true; } } }',
     "for i in $(seq 0 19); do"),
]

# M. Traps / cleanup patterns (B-1856..B-1865)
bash_entries += [
    ("B-1856", "r9-init-cleanup-sim", "Init and cleanup simulation", "standard",
     'fn main() { let initialized = true; let resource_count = 3; let mut cleaned = 0; for i in 0..3 { cleaned += 1; } }',
     "initialized=true"),
    ("B-1857", "r9-resource-counter", "Resource counter tracking", "standard",
     'fn main() { let mut allocated = 0; let mut freed = 0; for i in 0..5 { allocated += 1; } for i in 0..3 { freed += 1; } let leaked = allocated - freed; }',
     "leaked=$((allocated - freed))"),
    ("B-1858", "r9-retry-with-backoff", "Retry with exponential backoff simulation", "adversarial",
     'fn main() { let mut delay = 1; let mut attempt = 0; let max_attempts = 5; while attempt < max_attempts { delay = delay * 2; attempt += 1; } }',
     "while [ \"$attempt\" -lt \"$max_attempts\" ]; do"),
    ("B-1859", "r9-graceful-shutdown", "Graceful shutdown simulation", "production",
     'fn main() { let mut running = true; let mut processed = 0; let limit = 10; let mut i = 0; while i < limit { processed += 1; i += 1; } }',
     "while [ \"$i\" -lt \"$limit\" ]; do"),
    ("B-1860", "r9-lock-unlock-sim", "Lock/unlock simulation", "adversarial",
     'fn main() { let mut locked = false; locked = true; let work = 42 * 3; locked = false; let result = work + 1; }',
     "work=$((42 * 3))"),
    ("B-1861", "r9-transaction-sim", "Transaction simulation", "adversarial",
     'fn main() { let mut balance = 100; let mut tx_count = 0; balance = balance - 30; tx_count += 1; balance = balance + 50; tx_count += 1; balance = balance - 10; tx_count += 1; }',
     "balance=$((balance - 30))"),
    ("B-1862", "r9-health-check-sim", "Health check simulation", "production",
     'fn is_healthy(val: i32) -> bool { val > 0 && val < 100 } fn main() { let h1 = is_healthy(50); let h2 = is_healthy(0); let h3 = is_healthy(150); }',
     "is_healthy() {"),
    ("B-1863", "r9-timeout-sim", "Timeout simulation via counter", "standard",
     'fn main() { let timeout = 100; let mut elapsed = 0; while elapsed < timeout { elapsed += 10; } }',
     "while [ \"$elapsed\" -lt \"$timeout\" ]; do"),
    ("B-1864", "r9-cleanup-counter", "Cleanup with counter", "standard",
     'fn main() { let mut resources = 5; while resources > 0 { resources = resources - 1; } }',
     "while [ \"$resources\" -gt 0 ]; do"),
    ("B-1865", "r9-checkpoint-sim", "Checkpoint simulation at intervals", "adversarial",
     'fn main() { let mut step = 0; let mut checkpoints = 0; for i in 0..50 { step += 1; if step % 10 == 0 { checkpoints += 1; } } }',
     "for i in $(seq 0 49); do"),
]

# N. Command line parsing patterns (B-1866..B-1875)
bash_entries += [
    ("B-1866", "r9-flag-parser", "Flag parsing simulation", "adversarial",
     'fn parse_flags(verbose: bool, debug: bool) -> i32 { if verbose && debug { 3 } else if verbose { 2 } else if debug { 1 } else { 0 } } fn main() { let r = parse_flags(true, false); }',
     "parse_flags() {"),
    ("B-1867", "r9-arg-count-check", "Argument count validation", "standard",
     'fn validate_args(count: i32) -> bool { count >= 1 && count <= 5 } fn main() { let v1 = validate_args(0); let v2 = validate_args(3); let v3 = validate_args(10); }',
     "validate_args() {"),
    ("B-1868", "r9-option-handler", "Option handler dispatch", "adversarial",
     'fn handle_opt(opt: i32, val: i32) -> i32 { if opt == 0 { val + 10 } else if opt == 1 { val * 2 } else if opt == 2 { val - 5 } else { val } } fn main() { let r1 = handle_opt(0, 5); let r2 = handle_opt(1, 5); let r3 = handle_opt(2, 5); let r4 = handle_opt(99, 5); }',
     "handle_opt() {"),
    ("B-1869", "r9-priority-selector", "Priority selection function", "standard",
     'fn select(high: i32, med: i32, low: i32) -> i32 { if high > 0 { high } else if med > 0 { med } else { low } } fn main() { let r = select(0, 5, 10); }',
     "select() {"),
    ("B-1870", "r9-range-validator", "Range validation function", "standard",
     'fn in_range(val: i32, min: i32, max: i32) -> bool { val >= min && val <= max } fn main() { let v1 = in_range(5, 0, 10); let v2 = in_range(15, 0, 10); }',
     "in_range() {"),
    ("B-1871", "r9-mode-selector", "Mode selection with fallback", "adversarial",
     'fn mode(m: i32) -> i32 { if m == 1 { return 100; } if m == 2 { return 200; } if m == 3 { return 300; } return 0; } fn main() { let a = mode(1); let b = mode(2); let c = mode(99); }',
     "mode() {"),
    ("B-1872", "r9-config-merge", "Config merge simulation", "production",
     'fn merge(default_val: i32, override_val: i32) -> i32 { if override_val != 0 { override_val } else { default_val } } fn main() { let port = merge(8080, 0); let timeout = merge(30, 60); }',
     "merge() {"),
    ("B-1873", "r9-subcommand-router", "Subcommand router pattern", "adversarial",
     'fn run_cmd(cmd: i32, arg: i32) -> i32 { if cmd == 0 { arg + 1 } else if cmd == 1 { arg * 2 } else if cmd == 2 { arg / 2 } else if cmd == 3 { arg - 1 } else { 0 } } fn main() { let r1 = run_cmd(0, 10); let r2 = run_cmd(1, 10); let r3 = run_cmd(2, 10); let r4 = run_cmd(3, 10); }',
     "run_cmd() {"),
    ("B-1874", "r9-exit-code-mapper", "Exit code mapping function", "standard",
     'fn exit_code(success: bool) -> i32 { if success { 0 } else { 1 } } fn main() { let e1 = exit_code(true); let e2 = exit_code(false); }',
     "exit_code() {"),
    ("B-1875", "r9-threshold-check", "Multi-threshold check", "standard",
     'fn severity(level: i32) -> i32 { if level >= 90 { 4 } else if level >= 70 { 3 } else if level >= 50 { 2 } else { 1 } } fn main() { let s1 = severity(95); let s2 = severity(75); let s3 = severity(30); }',
     "severity() {"),
]

# O-P. Makefiles and Dockerfiles (B-1876..B-1885)
bash_entries += [
    ("B-1876", "r9-gcd-algorithm", "GCD algorithm (Euclidean)", "production",
     'fn gcd(a: i32, b: i32) -> i32 { let mut x = a; let mut y = b; while y != 0 { let tmp = y; y = x % y; x = tmp; } x } fn main() { let g = gcd(48, 18); }',
     "gcd() {"),
    ("B-1877", "r9-fibonacci-15th", "Fibonacci to 15th term", "production",
     'fn fib(n: i32) -> i32 { let mut a = 0; let mut b = 1; let mut i = 0; while i < n { let tmp = a + b; a = b; b = tmp; i += 1; } a } fn main() { let f = fib(15); }',
     "fib() {"),
    ("B-1878", "r9-collatz-steps", "Collatz conjecture step counter", "adversarial",
     'fn collatz(n: i32) -> i32 { let mut x = n; let mut steps = 0; while x > 1 { if x % 2 == 0 { x = x / 2; } else { x = x * 3 + 1; } steps += 1; } steps } fn main() { let s = collatz(27); }',
     "collatz() {"),
    ("B-1879", "r9-digit-sum", "Digital root via iterative summing", "adversarial",
     'fn digit_sum(n: i32) -> i32 { let mut x = n; let mut sum = 0; while x > 0 { sum += x % 10; x = x / 10; } sum } fn main() { let d = digit_sum(12345); }',
     "digit_sum() {"),
    ("B-1880", "r9-is-prime-check", "Primality check function", "production",
     'fn is_prime(n: i32) -> bool { if n < 2 { return false; } let mut i = 2; while i * i <= n { if n % i == 0 { return false; } i += 1; } true } fn main() { let p1 = is_prime(7); let p2 = is_prime(10); let p3 = is_prime(97); }',
     "is_prime() {"),
    ("B-1881", "r9-power-mod", "Modular exponentiation", "adversarial",
     'fn pow_mod(base: i32, exp: i32, modulus: i32) -> i32 { let mut result = 1; let mut i = 0; while i < exp { result = result * base % modulus; i += 1; } result } fn main() { let r = pow_mod(2, 10, 1000); }',
     "pow_mod() {"),
    ("B-1882", "r9-selection-sort-sim", "Selection sort simulation via comparisons", "adversarial",
     'fn main() { let mut a = 5; let mut b = 3; let mut c = 8; let mut d = 1; if a > b { let t = a; a = b; b = t; } if c > d { let t = c; c = d; d = t; } if a > c { let t = a; a = c; c = t; } if b > d { let t = b; b = d; d = t; } if b > c { let t = b; b = c; c = t; } }',
     "a='5'"),
    ("B-1883", "r9-prefix-sum", "Prefix sum array simulation", "adversarial",
     'fn main() { let a0 = 3; let a1 = 1; let a2 = 4; let a3 = 1; let a4 = 5; let p0 = a0; let p1 = p0 + a1; let p2 = p1 + a2; let p3 = p2 + a3; let p4 = p3 + a4; }',
     "p4=$((p3 + a4))"),
    ("B-1884", "r9-running-max", "Running maximum in loop", "production",
     'fn main() { let mut max = 0; for i in 0..15 { let val = (i * 7 + 13) % 20; if val > max { max = val; } } }',
     "for i in $(seq 0 14); do"),
    ("B-1885", "r9-newton-sqrt-sim", "Newton's method sqrt simulation", "adversarial",
     'fn sqrt_approx(n: i32) -> i32 { let mut guess = n / 2; let mut i = 0; while i < 10 { if guess == 0 { return 0; } guess = (guess + n / guess) / 2; i += 1; } guess } fn main() { let s = sqrt_approx(100); }',
     "sqrt_approx() {"),
]

# Q-W. Numerical methods, functional, etc. (B-1886..B-1905)
bash_entries += [
    ("B-1886", "r9-dot-product", "Dot product of two vectors", "adversarial",
     'fn main() { let a0 = 1; let a1 = 2; let a2 = 3; let b0 = 4; let b1 = 5; let b2 = 6; let dot = a0 * b0 + a1 * b1 + a2 * b2; }',
     "dot=$((a0 * b0 + a1 * b1 + a2 * b2))"),
    ("B-1887", "r9-linear-interp", "Linear interpolation", "adversarial",
     'fn lerp(a: i32, b: i32, t_num: i32, t_den: i32) -> i32 { a + (b - a) * t_num / t_den } fn main() { let r = lerp(0, 100, 1, 4); }',
     "lerp() {"),
    ("B-1888", "r9-matrix-trace", "Matrix trace (sum of diagonal)", "standard",
     'fn main() { let m00 = 1; let m11 = 5; let m22 = 9; let trace = m00 + m11 + m22; }',
     "trace=$((m00 + m11 + m22))"),
    ("B-1889", "r9-harmonic-sum-int", "Harmonic-like integer sum", "adversarial",
     'fn main() { let mut sum = 0; for i in 1..11 { sum += 100 / i; } }',
     "sum=$((sum + 100 / i))"),
    ("B-1890", "r9-taylor-approx-int", "Taylor-like integer approximation", "adversarial",
     'fn main() { let mut result = 1; let mut term = 1; for i in 1..6 { term = term * 10 / i; result += term; } }',
     "for i in $(seq 1 5); do"),
    ("B-1891", "r9-compose-3func", "Functional composition of 3 functions", "adversarial",
     'fn double(x: i32) -> i32 { x * 2 } fn add5(x: i32) -> i32 { x + 5 } fn mod7(x: i32) -> i32 { x % 7 } fn compose(x: i32) -> i32 { mod7(add5(double(x))) } fn main() { let r = compose(10); }',
     "compose() {"),
    ("B-1892", "r9-fold-sim", "Fold simulation over range", "production",
     'fn main() { let mut acc = 0; for i in 1..11 { acc = acc + i; } }',
     "acc=$((acc + i))"),
    ("B-1893", "r9-apply-twice", "Apply function twice pattern", "adversarial",
     'fn apply_twice(x: i32) -> i32 { let first = x * 2 + 1; first * 2 + 1 } fn main() { let r = apply_twice(5); }',
     "apply_twice() {"),
    ("B-1894", "r9-predicate-filter", "Predicate-based filtering", "standard",
     'fn is_valid(x: i32) -> bool { x > 0 && x % 2 == 0 } fn main() { let mut count = 0; for i in 0..20 { if is_valid(i) { count += 1; } } }',
     "is_valid() {"),
    ("B-1895", "r9-binary-digits", "Count binary digits", "adversarial",
     'fn bit_count(n: i32) -> i32 { let mut x = n; let mut bits = 0; while x > 0 { bits += 1; x = x / 2; } bits } fn main() { let b = bit_count(255); }',
     "bit_count() {"),
    ("B-1896", "r9-popcount", "Population count (bit counting sim)", "adversarial",
     'fn popcount(n: i32) -> i32 { let mut x = n; let mut count = 0; while x > 0 { count += x % 2; x = x / 2; } count } fn main() { let p = popcount(255); }',
     "popcount() {"),
    ("B-1897", "r9-hex-digit-sim", "Hex digit extraction simulation", "adversarial",
     'fn hex_digit(n: i32) -> i32 { n % 16 } fn main() { let d0 = hex_digit(255); let d1 = hex_digit(255 / 16); }',
     "hex_digit() {"),
    ("B-1898", "r9-celsius-to-fahr", "Temperature conversion", "standard",
     'fn c_to_f(c: i32) -> i32 { c * 9 / 5 + 32 } fn main() { let f1 = c_to_f(0); let f2 = c_to_f(100); let f3 = c_to_f(37); }',
     "c_to_f() {"),
    ("B-1899", "r9-distance-manhattan", "Manhattan distance calculation", "standard",
     'fn manhattan(x1: i32, y1: i32, x2: i32, y2: i32) -> i32 { let dx = x2 - x1; let ax = if dx < 0 { 0 - dx } else { dx }; let dy = y2 - y1; let ay = if dy < 0 { 0 - dy } else { dy }; ax + ay } fn main() { let d = manhattan(1, 2, 4, 6); }',
     "manhattan() {"),
    ("B-1900", "r9-enum-dispatch", "Enum-like dispatch via match", "adversarial",
     'fn color_val(c: u32) -> u32 { match c { 0 => { return 255; } 1 => { return 128; } 2 => { return 64; } 3 => { return 32; } _ => { return 0; } } } fn main() { let r = color_val(0); let g = color_val(1); let b = color_val(2); }',
     "color_val() {"),
    ("B-1901", "r9-bitwise-sim", "Bitwise operations simulation", "adversarial",
     'fn main() { let a = 170; let b = 85; let and_val = a / 256 * 256; let or_val = a + b; let xor_val = a + b - 2 * (a / 256 * 256); }',
     "or_val=$((a + b))"),
    ("B-1902", "r9-sieve-sim", "Sieve of Eratosthenes simulation (small)", "adversarial",
     'fn main() { let mut count = 0; for i in 2..20 { let mut is_prime = true; let mut j = 2; while j * j <= i { if i % j == 0 { is_prime = false; break; } j += 1; } if is_prime { count += 1; } } }',
     "for i in $(seq 2 19); do"),
    ("B-1903", "r9-permutation-count", "Permutation counting", "production",
     'fn perm(n: i32, r: i32) -> i32 { let mut result = 1; let mut i = 0; while i < r { result = result * (n - i); i += 1; } result } fn main() { let p = perm(5, 3); }',
     "perm() {"),
    ("B-1904", "r9-combination-sim", "Combination via factorial division", "adversarial",
     'fn fact(n: i32) -> i32 { let mut r = 1; let mut i = 1; while i <= n { r = r * i; i += 1; } r } fn comb(n: i32, k: i32) -> i32 { fact(n) / (fact(k) * fact(n - k)) } fn main() { let c = comb(10, 3); }',
     "comb() {"),
    ("B-1905", "r9-moving-average", "Moving average simulation", "production",
     'fn main() { let mut sum = 0; let window = 3; for i in 1..11 { sum += i; if i >= window { let avg = sum / window; sum = sum - (i - window + 1); } } }',
     "for i in $(seq 1 10); do"),
]

# ============================================================
# Makefile entries M-421..M-435
# ============================================================
makefile_entries = [
    ("M-421", "r9-docker-compose-mk", "Docker Compose Makefile", "adversarial",
     'fn main() { exec(".PHONY: up down restart logs"); exec("up:"); exec("\\tdocker compose up -d"); exec("down:"); exec("\\tdocker compose down"); exec("restart: down up"); exec("logs:"); exec("\\tdocker compose logs -f"); }',
     "docker compose up -d"),
    ("M-422", "r9-python-venv-mk", "Python virtualenv Makefile", "adversarial",
     'fn main() { exec(".PHONY: venv install test clean"); exec("venv:"); exec("\\tpython3 -m venv .venv"); exec("install: venv"); exec("\\t.venv/bin/pip install -r requirements.txt"); exec("test: install"); exec("\\t.venv/bin/pytest"); exec("clean:"); exec("\\trm -rf .venv"); }',
     "python3 -m venv .venv"),
    ("M-423", "r9-go-build-mk", "Go build and test Makefile", "production",
     'fn main() { exec(".PHONY: build test lint clean"); exec("build:"); exec("\\tgo build -o bin/app ./cmd/app"); exec("test:"); exec("\\tgo test ./..."); exec("lint:"); exec("\\tgolangci-lint run"); exec("clean:"); exec("\\trm -rf bin/"); }',
     "go build -o bin/app ./cmd/app"),
    ("M-424", "r9-npm-scripts-mk", "npm scripts Makefile", "standard",
     'fn main() { exec(".PHONY: install dev build test"); exec("install:"); exec("\\tnpm ci"); exec("dev:"); exec("\\tnpm run dev"); exec("build: install"); exec("\\tnpm run build"); exec("test: install"); exec("\\tnpm test"); }',
     "npm ci"),
    ("M-425", "r9-release-mk", "Release automation Makefile", "adversarial",
     'fn main() { exec("VERSION := 1.0.0"); exec(".PHONY: release tag push"); exec("release: tag push"); exec("tag:"); exec("\\tgit tag -a v$(VERSION) -m Release"); exec("push:"); exec("\\tgit push origin main --tags"); }',
     "VERSION := 1.0.0"),
    ("M-426", "r9-migrate-mk", "Database migration Makefile", "production",
     'fn main() { exec(".PHONY: migrate rollback seed"); exec("migrate:"); exec("\\tpython manage.py migrate"); exec("rollback:"); exec("\\tpython manage.py migrate --fake zero"); exec("seed:"); exec("\\tpython manage.py loaddata fixtures/*.json"); }',
     "python manage.py migrate"),
    ("M-427", "r9-terraform-mk", "Terraform workflow Makefile", "adversarial",
     'fn main() { exec(".PHONY: init plan apply destroy"); exec("init:"); exec("\\tterraform init"); exec("plan: init"); exec("\\tterraform plan -out=tfplan"); exec("apply:"); exec("\\tterraform apply tfplan"); exec("destroy:"); exec("\\tterraform destroy -auto-approve"); }',
     "terraform init"),
    ("M-428", "r9-protobuf-mk", "Protobuf generation Makefile", "adversarial",
     'fn main() { exec(".PHONY: proto clean"); exec("proto:"); exec("\\tprotoc --go_out=. --go-grpc_out=. proto/*.proto"); exec("clean:"); exec("\\trm -rf gen/"); }',
     "protoc --go_out=. --go-grpc_out=. proto/*.proto"),
    ("M-429", "r9-latex-mk", "LaTeX document build Makefile", "standard",
     'fn main() { exec(".PHONY: pdf clean"); exec("pdf:"); exec("\\tpdflatex main.tex"); exec("\\tbibtex main"); exec("\\tpdflatex main.tex"); exec("\\tpdflatex main.tex"); exec("clean:"); exec("\\trm -f *.aux *.log *.bbl *.blg"); }',
     "pdflatex main.tex"),
    ("M-430", "r9-k8s-deploy-mk", "Kubernetes deployment Makefile", "adversarial",
     'fn main() { exec(".PHONY: deploy rollback status"); exec("deploy:"); exec("\\tkubectl apply -f k8s/"); exec("rollback:"); exec("\\tkubectl rollout undo deployment/app"); exec("status:"); exec("\\tkubectl get pods"); }',
     "kubectl apply -f k8s/"),
    ("M-431", "r9-rust-workspace-mk", "Rust workspace Makefile", "production",
     'fn main() { exec(".PHONY: build test clippy fmt check"); exec("build:"); exec("\\tcargo build --workspace"); exec("test:"); exec("\\tcargo test --workspace"); exec("clippy:"); exec("\\tcargo clippy --workspace -- -D warnings"); exec("fmt:"); exec("\\tcargo fmt --all -- --check"); exec("check: clippy fmt test"); }',
     "cargo build --workspace"),
    ("M-432", "r9-static-site-mk", "Static site generator Makefile", "standard",
     'fn main() { exec(".PHONY: build serve deploy clean"); exec("build:"); exec("\\thugo --minify"); exec("serve:"); exec("\\thugo server -D"); exec("deploy: build"); exec("\\trsync -avz public/ user@host:/var/www/"); exec("clean:"); exec("\\trm -rf public/"); }',
     "hugo --minify"),
    ("M-433", "r9-android-mk", "Android build Makefile", "adversarial",
     'fn main() { exec(".PHONY: debug release clean install"); exec("debug:"); exec("\\t./gradlew assembleDebug"); exec("release:"); exec("\\t./gradlew assembleRelease"); exec("clean:"); exec("\\t./gradlew clean"); exec("install: debug"); exec("\\tadb install app/build/outputs/apk/debug/app-debug.apk"); }',
     "./gradlew assembleDebug"),
    ("M-434", "r9-benchmark-mk", "Benchmark runner Makefile", "production",
     'fn main() { exec(".PHONY: bench bench-save compare"); exec("bench:"); exec("\\tcargo bench"); exec("bench-save:"); exec("\\tcargo bench -- --save-baseline main"); exec("compare:"); exec("\\tcritcmp main new"); }',
     "cargo bench"),
    ("M-435", "r9-docs-mk", "Documentation build Makefile", "standard",
     'fn main() { exec(".PHONY: docs serve publish"); exec("docs:"); exec("\\tmdbook build"); exec("serve:"); exec("\\tmdbook serve"); exec("publish: docs"); exec("\\taws s3 sync book/ s3://docs-bucket/"); }',
     "mdbook build"),
]

# ============================================================
# Dockerfile entries D-381..D-400
# ============================================================
dockerfile_entries = [
    ("D-381", "r9-elixir-phoenix", "Elixir Phoenix app", "adversarial",
     'fn main() { from_image("elixir:1.16-alpine"); workdir("/app"); copy("mix.exs mix.lock", "./"); run("mix deps.get"); copy(".", "."); run("mix compile"); expose(4000); cmd("mix phx.server"); }',
     "FROM elixir:1.16-alpine"),
    ("D-382", "r9-dotnet-sdk", ".NET SDK build", "adversarial",
     'fn main() { from_image("mcr.microsoft.com/dotnet/sdk:8.0"); workdir("/src"); copy("*.csproj", "./"); run("dotnet restore"); copy(".", "."); run("dotnet publish -c Release -o /app"); }',
     "FROM mcr.microsoft.com/dotnet/sdk:8.0"),
    ("D-383", "r9-python-uvicorn", "Python FastAPI with uvicorn", "adversarial",
     'fn main() { from_image("python:3.12-slim"); workdir("/app"); copy("requirements.txt", "."); run("pip install --no-cache-dir -r requirements.txt"); copy(".", "."); expose(8000); cmd("uvicorn main:app --host 0.0.0.0 --port 8000"); }',
     "FROM python:3.12-slim"),
    ("D-384", "r9-redis-custom", "Redis with custom config", "adversarial",
     'fn main() { from_image("redis:7-alpine"); copy("redis.conf", "/usr/local/etc/redis/redis.conf"); expose(6379); cmd("redis-server /usr/local/etc/redis/redis.conf"); }',
     "FROM redis:7-alpine"),
    ("D-385", "r9-nginx-proxy", "Nginx reverse proxy", "adversarial",
     'fn main() { from_image("nginx:alpine"); copy("nginx.conf", "/etc/nginx/nginx.conf"); expose(80); expose(443); cmd("nginx -g daemon off;"); }',
     "FROM nginx:alpine"),
    ("D-386", "r9-postgres-init", "PostgreSQL with init script", "production",
     'fn main() { from_image("postgres:16-alpine"); copy("init.sql", "/docker-entrypoint-initdb.d/"); expose(5432); }',
     "FROM postgres:16-alpine"),
    ("D-387", "r9-ruby-rails", "Ruby on Rails app", "adversarial",
     'fn main() { from_image("ruby:3.3-slim"); workdir("/app"); copy("Gemfile Gemfile.lock", "./"); run("bundle install"); copy(".", "."); expose(3000); cmd("rails server -b 0.0.0.0"); }',
     "FROM ruby:3.3-slim"),
    ("D-388", "r9-java-spring", "Java Spring Boot app", "production",
     'fn main() { from_image("eclipse-temurin:21-jdk-alpine"); workdir("/app"); copy("build.gradle settings.gradle", "./"); copy("src/", "src/"); run("./gradlew bootJar"); expose(8080); cmd("java -jar build/libs/app.jar"); }',
     "FROM eclipse-temurin:21-jdk-alpine"),
    ("D-389", "r9-rust-builder", "Rust builder image", "production",
     'fn main() { from_image("rust:1.77-alpine"); run("apk add --no-cache musl-dev"); workdir("/app"); copy("Cargo.toml Cargo.lock", "./"); copy("src/", "src/"); run("cargo build --release"); }',
     "FROM rust:1.77-alpine"),
    ("D-390", "r9-node-next", "Next.js app", "adversarial",
     'fn main() { from_image("node:20-alpine"); workdir("/app"); copy("package.json package-lock.json", "./"); run("npm ci"); copy(".", "."); run("npm run build"); expose(3000); cmd("npm start"); }',
     "FROM node:20-alpine"),
    ("D-391", "r9-deno-server", "Deno HTTP server", "adversarial",
     'fn main() { from_image("denoland/deno:1.40"); workdir("/app"); copy(".", "."); expose(8000); cmd("deno run --allow-net main.ts"); }',
     "FROM denoland/deno:1.40"),
    ("D-392", "r9-golang-grpc", "Go gRPC service", "production",
     'fn main() { from_image("golang:1.22-alpine"); workdir("/build"); copy("go.mod go.sum", "./"); run("go mod download"); copy(".", "."); run("go build -o /app ./cmd/server"); expose(50051); }',
     "FROM golang:1.22-alpine"),
    ("D-393", "r9-python-celery", "Python Celery worker", "adversarial",
     'fn main() { from_image("python:3.12-slim"); workdir("/app"); copy("requirements.txt", "."); run("pip install -r requirements.txt"); copy(".", "."); cmd("celery -A tasks worker --loglevel=info"); }',
     "FROM python:3.12-slim"),
    ("D-394", "r9-mongo-init", "MongoDB with initialization", "standard",
     'fn main() { from_image("mongo:7"); copy("init-mongo.js", "/docker-entrypoint-initdb.d/"); expose(27017); }',
     "FROM mongo:7"),
    ("D-395", "r9-grafana-custom", "Grafana with custom dashboards", "adversarial",
     'fn main() { from_image("grafana/grafana:10.3"); copy("dashboards/", "/var/lib/grafana/dashboards/"); copy("provisioning/", "/etc/grafana/provisioning/"); expose(3000); }',
     "FROM grafana/grafana:10.3"),
    ("D-396", "r9-php-laravel", "PHP Laravel app", "adversarial",
     'fn main() { from_image("php:8.3-fpm-alpine"); workdir("/app"); run("docker-php-ext-install pdo_mysql"); copy("composer.json composer.lock", "./"); run("composer install --no-dev"); copy(".", "."); expose(9000); }',
     "FROM php:8.3-fpm-alpine"),
    ("D-397", "r9-scala-sbt", "Scala SBT project", "adversarial",
     'fn main() { from_image("sbtscala/scala-sbt:17.0.9_1.9.8_3.3.1"); workdir("/app"); copy("build.sbt", "."); copy("project/", "project/"); run("sbt compile"); copy("src/", "src/"); run("sbt assembly"); }',
     "FROM sbtscala/scala-sbt:17.0.9_1.9.8_3.3.1"),
    ("D-398", "r9-prometheus-config", "Prometheus with custom config", "standard",
     'fn main() { from_image("prom/prometheus:v2.49"); copy("prometheus.yml", "/etc/prometheus/prometheus.yml"); expose(9090); cmd("--config.file=/etc/prometheus/prometheus.yml"); }',
     "FROM prom/prometheus:v2.49"),
    ("D-399", "r9-traefik-proxy", "Traefik reverse proxy", "adversarial",
     'fn main() { from_image("traefik:v3.0"); copy("traefik.yml", "/etc/traefik/traefik.yml"); expose(80); expose(443); expose(8080); }',
     "FROM traefik:v3.0"),
    ("D-400", "r9-minio-storage", "MinIO object storage", "standard",
     'fn main() { from_image("minio/minio:latest"); expose(9000); expose(9001); cmd("minio server /data --console-address :9001"); }',
     "FROM minio/minio:latest"),
]

# ============================================================
# Output
# ============================================================

lines = []

# Bash function
lines.append('    /// Round 9 Bash: B-1706..B-1905 — 200 entries with B2-optimized expected strings')
lines.append('    fn load_expansion44_bash(&mut self) {')
lines.append('        let entries = vec![')
for e in bash_entries:
    lines.append(entry(e[0], e[1], e[2], "bash", e[3], e[4], e[5]))
lines.append('        ];')
lines.append('        for entry in entries {')
lines.append('            self.entries.push(entry);')
lines.append('        }')
lines.append('    }')
lines.append('')

# Makefile function
lines.append('    /// Round 9 Makefile: M-421..M-435')
lines.append('    fn load_expansion32_makefile(&mut self) {')
lines.append('        let entries = vec![')
for e in makefile_entries:
    lines.append(entry(e[0], e[1], e[2], "makefile", e[3], e[4], e[5]))
lines.append('        ];')
lines.append('        for entry in entries {')
lines.append('            self.entries.push(entry);')
lines.append('        }')
lines.append('    }')
lines.append('')

# Dockerfile function
lines.append('    /// Round 9 Dockerfile: D-381..D-400')
lines.append('    fn load_expansion32_dockerfile(&mut self) {')
lines.append('        let entries = vec![')
for e in dockerfile_entries:
    lines.append(entry(e[0], e[1], e[2], "dockerfile", e[3], e[4], e[5]))
lines.append('        ];')
lines.append('        for entry in entries {')
lines.append('            self.entries.push(entry);')
lines.append('        }')
lines.append('    }')

print('\n'.join(lines))
