fn generate_installer_scaffold(
    description: &str,
    target_os: &[String],
    author: Option<&str>,
) -> (String, usize) {
    let project_name = generate_project_name(description);
    let author_str = author.unwrap_or("bashrs team");
    let os_list: Vec<String> = target_os.iter().map(|s| format!("\"{}\"", s)).collect();

    // Detect common patterns and generate appropriate steps
    let desc_lower = description.to_lowercase();
    let mut steps = Vec::new();
    let mut step_count = 0;

    // System dependencies step
    steps.push(format!(
        r#"[[step]]
id = "install-deps"
name = "Install System Dependencies"
action = "apt-install"
packages = ["curl", "ca-certificates"]

[step.postconditions]
command_succeeds = "which curl"

[step.checkpoint]
enabled = true

[step.timing]
timeout = "10m""#
    ));
    step_count += 1;

    // Add package-specific steps based on description
    if desc_lower.contains("postgresql") || desc_lower.contains("postgres") {
        steps.push(format!(
            r#"
[[step]]
id = "add-postgres-repo"
name = "Add PostgreSQL APT Repository"
action = "script"
depends_on = ["install-deps"]

[step.script]
interpreter = "sh"
content = '''
curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /usr/share/keyrings/postgresql.gpg
echo "deb [signed-by=/usr/share/keyrings/postgresql.gpg] http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
apt-get update
'''

[step.postconditions]
file_exists = "/etc/apt/sources.list.d/pgdg.list"

[step.checkpoint]
enabled = true

[[step]]
id = "install-postgresql"
name = "Install PostgreSQL"
action = "apt-install"
depends_on = ["add-postgres-repo"]
packages = ["postgresql-16", "postgresql-client-16"]

[step.postconditions]
command_succeeds = "pg_isready"

[step.checkpoint]
enabled = true

[step.timing]
timeout = "15m""#
        ));
        step_count += 2;
    }

    if desc_lower.contains("docker") {
        steps.push(format!(
            r#"
[[step]]
id = "install-docker"
name = "Install Docker"
action = "script"
depends_on = ["install-deps"]

[step.script]
interpreter = "sh"
content = '''
curl -fsSL https://get.docker.com | sh
usermod -aG docker $SUDO_USER || true
'''

[step.postconditions]
command_succeeds = "docker --version"

[step.checkpoint]
enabled = true

[step.timing]
timeout = "15m""#
        ));
        step_count += 1;
    }

    if desc_lower.contains("rust") || desc_lower.contains("cargo") {
        steps.push(format!(
            r#"
[[step]]
id = "install-rust"
name = "Install Rust Toolchain"
action = "script"
depends_on = ["install-deps"]

[step.script]
interpreter = "sh"
content = '''
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
. "$HOME/.cargo/env"
'''

[step.postconditions]
command_succeeds = "rustc --version"

[step.checkpoint]
enabled = true

[step.timing]
timeout = "10m""#
        ));
        step_count += 1;
    }

    if desc_lower.contains("node") || desc_lower.contains("npm") {
        steps.push(format!(
            r#"
[[step]]
id = "install-node"
name = "Install Node.js"
action = "script"
depends_on = ["install-deps"]

[step.script]
interpreter = "sh"
content = '''
curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
apt-get install -y nodejs
'''

[step.postconditions]
command_succeeds = "node --version"

[step.checkpoint]
enabled = true

[step.timing]
timeout = "10m""#
        ));
        step_count += 1;
    }

    // Verification step
    steps.push(format!(
        r#"
[[step]]
id = "verify-installation"
name = "Verify Installation"
action = "script"
depends_on = [{}]

[step.script]
interpreter = "sh"
content = '''
echo "Installation complete!"
echo "Verifying components..."
'''

[step.checkpoint]
enabled = true

[step.timing]
timeout = "2m""#,
        if step_count > 1 {
            steps
                .iter()
                .skip(1)
                .filter_map(|s| {
                    s.lines()
                        .find(|l| l.starts_with("id = "))
                        .map(|l| l.replace("id = ", "").replace("\"", ""))
                })
                .map(|id| format!("\"{}\"", id))
                .collect::<Vec<_>>()
                .join(", ")
        } else {
            "\"install-deps\"".to_string()
        }
    ));
    step_count += 1;

    let installer_toml = format!(
        r#"# Installer generated by bashrs MCP
# Description: {description}

[installer]
name = "{project_name}"
version = "1.0.0"
description = "{description}"
author = "{author_str}"

[installer.requirements]
os = [{os_list}]
arch = ["x86_64", "aarch64"]
privileges = "root"
network = true

[installer.security]
trust_model = "tofu"
require_signatures = false

{steps}
"#,
        os_list = os_list.join(", "),
        steps = steps.join("\n")
    );

    (installer_toml, step_count)
}

fn suggest_next_step(
    current_steps: &[String],
    goal: &str,
    step_ids: &[String],
) -> (String, String, String, Vec<String>, Vec<String>) {
    let goal_lower = goal.to_lowercase();
    let has_deps = current_steps
        .iter()
        .any(|s| s.contains("apt-install") || s.contains("install-deps"));
    let has_config = current_steps.iter().any(|s| s.contains("configure"));

    // Determine the best next step based on goal and current state
    let (step_template, step_id, rationale) = if !has_deps {
        (
            r#"[[step]]
id = "install-deps"
name = "Install System Dependencies"
action = "apt-install"
packages = ["curl", "ca-certificates"]

[step.postconditions]
command_succeeds = "which curl"

[step.checkpoint]
enabled = true

[step.timing]
timeout = "10m""#
                .to_string(),
            "install-deps".to_string(),
            "Every installer should start with system dependencies".to_string(),
        )
    } else if goal_lower.contains("config") && !has_config {
        (
            r#"[[step]]
id = "configure-app"
name = "Configure Application"
action = "script"

[step.script]
interpreter = "sh"
content = '''
# Add configuration here
mkdir -p /etc/myapp
'''

[step.postconditions]
file_exists = "/etc/myapp"

[step.checkpoint]
enabled = true

[step.timing]
timeout = "5m""#
                .to_string(),
            "configure-app".to_string(),
            "Configuration step needed based on goal".to_string(),
        )
    } else {
        (
            r#"[[step]]
id = "verify-installation"
name = "Verify Installation"
action = "script"

[step.script]
interpreter = "sh"
content = '''
echo "Verifying installation..."
'''

[step.checkpoint]
enabled = true

[step.timing]
timeout = "2m""#
                .to_string(),
            "verify-installation".to_string(),
            "Verification step ensures installation completed correctly".to_string(),
        )
    };

    let depends_on: Vec<String> = if !step_ids.is_empty() {
        vec![step_ids.last().cloned().unwrap_or_default()]
    } else {
        vec![]
    };

    let alternatives = vec![
        "Consider adding a rollback step for safety".to_string(),
        "Add postconditions to verify step success".to_string(),
    ];

    (step_template, step_id, rationale, depends_on, alternatives)
}

fn validate_installer_toml(
    value: &toml::Value,
    security_focus: bool,
) -> (Vec<ValidationIssue>, Vec<ValidationIssue>, Vec<String>, u32) {
    let mut errors = Vec::new();
    let mut warnings = Vec::new();
    let mut suggestions = Vec::new();
    let mut score = 100u32;

    // Check for [installer] section
    if value.get("installer").is_none() {
        errors.push(ValidationIssue {
            code: "STRUCT001".to_string(),
            message: "Missing [installer] section".to_string(),
            location: None,
            fix: Some("Add [installer] section with name, version, description".to_string()),
        });
        score = score.saturating_sub(20);
    } else {
        let installer = value.get("installer").expect("checked above");
        if installer.get("name").is_none() {
            errors.push(ValidationIssue {
                code: "STRUCT002".to_string(),
                message: "Missing installer.name".to_string(),
                location: Some("installer".to_string()),
                fix: Some("Add name = \"my-installer\"".to_string()),
            });
            score = score.saturating_sub(10);
        }
        if installer.get("version").is_none() {
            warnings.push(ValidationIssue {
                code: "STRUCT003".to_string(),
                message: "Missing installer.version".to_string(),
                location: Some("installer".to_string()),
                fix: Some("Add version = \"1.0.0\"".to_string()),
            });
            score = score.saturating_sub(5);
        }
    }

    // Check for steps
    let steps = value.get("step").and_then(|s| s.as_array());
    if steps.is_none() || steps.is_some_and(|s| s.is_empty()) {
        errors.push(ValidationIssue {
            code: "STRUCT010".to_string(),
            message: "No steps defined".to_string(),
            location: None,
            fix: Some("Add at least one [[step]] section".to_string()),
        });
        score = score.saturating_sub(30);
    }

    // Security checks
    if security_focus {
        if let Some(steps) = steps {
            for (i, step) in steps.iter().enumerate() {
                let default_id = format!("step-{}", i);
                let step_id = step
                    .get("id")
                    .and_then(|v| v.as_str())
                    .unwrap_or(&default_id);

                // Check for script content
                if let Some(script) = step.get("script").and_then(|s| s.get("content")) {
                    if let Some(content) = script.as_str() {
                        // Check for dangerous patterns
                        if content.contains("curl") && content.contains("| sh") {
                            warnings.push(ValidationIssue {
                                code: "SEC001".to_string(),
                                message: "Piping curl to shell is risky".to_string(),
                                location: Some(step_id.to_string()),
                                fix: Some(
                                    "Download script first, verify, then execute".to_string(),
                                ),
                            });
                            score = score.saturating_sub(10);
                        }
                        if content.contains("chmod 777") {
                            warnings.push(ValidationIssue {
                                code: "SEC002".to_string(),
                                message: "chmod 777 is overly permissive".to_string(),
                                location: Some(step_id.to_string()),
                                fix: Some(
                                    "Use chmod 755 for executables, 644 for files".to_string(),
                                ),
                            });
                            score = score.saturating_sub(5);
                        }
                    }
                }

                // Check for postconditions
                if step.get("postconditions").is_none() {
                    suggestions.push(format!("Step '{}' has no postconditions", step_id));
                }

                // Check for checkpoint
                if step.get("checkpoint").is_none() {
                    suggestions.push(format!("Step '{}' has no checkpoint", step_id));
                }
            }
        }
    }

    (errors, warnings, suggestions, score)
}


include!("installer_incl2_incl2.rs");
