#!/bin/bash
# Generated pre-commit hook (auto-managed by PMAT)
# DO NOT EDIT: This file is automatically generated
# Generated at: 2026-02-05 17:08:41

set -e

echo "🔍 PMAT Pre-commit Quality Gates"
echo "================================"

# Load current configuration dynamically
export PMAT_MAX_CYCLOMATIC_COMPLEXITY=30
export PMAT_MAX_COGNITIVE_COMPLEXITY=25
export PMAT_MIN_TEST_COVERAGE=80
export PMAT_MAX_SATD_COMMENTS=5
export PMAT_TASK_ID_PATTERN="PMAT-[0-9]{4}"

# Check if pmat is available
if ! command -v pmat &> /dev/null; then
    echo "⚠️  Warning: pmat not found in PATH"
    echo "   Install with: cargo install pmat"
    exit 0  # Allow commit but warn
fi

echo "📊 Running quality gate checks..."

# 1. Complexity analysis (only staged .rs files, not entire project)
STAGED_RS=$(git diff --cached --name-only --diff-filter=ACMR -- '*.rs' | head -20)
if [ -n "$STAGED_RS" ]; then
    echo -n "  Complexity check... "
    COMPLEXITY_FAILED=0
    COMPLEXITY_DETAILS=""
    for RS_FILE in $STAGED_RS; do
        if [ -f "$RS_FILE" ]; then
            FILE_OUTPUT=$(pmat analyze complexity --path "$RS_FILE" --max-cyclomatic $PMAT_MAX_CYCLOMATIC_COMPLEXITY --max-cognitive $PMAT_MAX_COGNITIVE_COMPLEXITY 2>&1)
            if echo "$FILE_OUTPUT" | grep -q 'Errors.*: [1-9]'; then
                COMPLEXITY_FAILED=1
                # Extract the offending file and functions
                COMPLEXITY_DETAILS="${COMPLEXITY_DETAILS}  ${RS_FILE}:"$'\n'
                FILE_VIOLATIONS=$(echo "$FILE_OUTPUT" | grep -E '^[0-9]+\. ' | grep -E 'Cyclomatic|Cognitive' | head -3)
                COMPLEXITY_DETAILS="${COMPLEXITY_DETAILS}${FILE_VIOLATIONS}"$'\n'
            fi
        fi
    done
    if [ "$COMPLEXITY_FAILED" -eq 0 ]; then
        echo "✅"
    else
        echo "❌"
        echo "Issues Found:"
        echo "$COMPLEXITY_DETAILS" | head -10
        echo "   Complexity exceeds thresholds (Cyclomatic: $PMAT_MAX_CYCLOMATIC_COMPLEXITY, Cognitive: $PMAT_MAX_COGNITIVE_COMPLEXITY)"
        exit 1
    fi
else
    echo "  Complexity check... ⏭️  (no .rs files staged)"
fi

# 2. SATD (Self-Admitted Quality Issues) check - informational only
echo -n "  SATD check... "
SATD_OUTPUT=$(pmat analyze satd 2>&1)
SATD_COUNT=$(echo "$SATD_OUTPUT" | grep -oP 'Total SATD comments found: \K[0-9]+' || echo "0")
if [ "$SATD_COUNT" -le "$PMAT_MAX_SATD_COMMENTS" ] 2>/dev/null; then
    echo "✅ ($SATD_COUNT SATD comments)"
else
    echo "⚠️  ($SATD_COUNT SATD comments, threshold: $PMAT_MAX_SATD_COMMENTS)"
fi

# 3. Documentation synchronization
echo -n "  Documentation check... "
if [ -f "docs/execution/roadmap.md" ] && [ -f "CHANGELOG.md" ]; then
    echo "✅"
else
    echo "⚠️"
    echo "   Warning: Required documentation files missing"
fi

# 4. Task ID validation (if commit message available)
if [ -n "$1" ]; then
    echo -n "  Task ID check... "
    if echo "$1" | grep -qE "$PMAT_TASK_ID_PATTERN"; then
        echo "✅"
    else
        echo "⚠️"
        echo "   Warning: Commit message should contain task ID matching $PMAT_TASK_ID_PATTERN"
    fi
fi

echo ""
echo "✅ All quality gates passed!"
echo ""

# Success
exit 0
